import { Award, Compass, Eye, GraduationCap, HeartHandshake, Lightbulb, Route, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/ui/page-hero";
import { SectionHeading } from "@/components/ui/section-heading";
import { Card } from "@/components/ui/card";
import { Counter } from "@/components/shared/counter";
import { ContactCta } from "@/components/sections/contact-cta";
import { BreadcrumbJsonLd } from "@/components/seo/json-ld";
import { createMetadata } from "@/lib/seo";
import { stats } from "@/data/site";

export const metadata = createMetadata("About", "Learn about Engineer Mumtaz Ali's engineering approach, career journey, values, mission, and professional philosophy.", "/about");

const timeline = [
  { period: "Foundation", title: "Programming and web fundamentals", text: "Built a practical base across programming logic, responsive frontend development, databases, and problem solving." },
  { period: "Specialization", title: "WordPress, Elementor, and commerce", text: "Developed deep capability in editor-friendly WordPress systems, WooCommerce flows, responsive layouts, and client delivery." },
  { period: "Product Engineering", title: "React, Next.js, APIs, and architecture", text: "Expanded into typed component systems, server-rendered applications, backend services, technical SEO, and performance engineering." },
  { period: "Current Direction", title: "End-to-end digital product delivery", text: "Combining engineering, UX judgment, maintainable systems, and business context to deliver higher-value outcomes." }
];

const values = [
  { icon: ShieldCheck, title: "Reliability", text: "Design choices and code decisions should remain dependable after handoff." },
  { icon: Lightbulb, title: "Clarity", text: "Complex requirements become stronger when they are organized into a simple system." },
  { icon: HeartHandshake, title: "Ownership", text: "I treat the full result—not only assigned tasks—as the unit of responsibility." },
  { icon: Compass, title: "Continuous improvement", text: "Every project should improve the process, standards, and reusable knowledge behind the next one." }
];

export default function AboutPage() {
  return <><BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: "About", path: "/about" }]} /><PageHero eyebrow="About the engineer" title="Product thinking, engineering discipline, and attention to detail." description="A cross-functional web engineer focused on building clear, maintainable, responsive, and credible digital experiences." />
  <section className="section-space bg-white"><div className="container-shell grid gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><SectionHeading eyebrow="Biography" title="I build at the intersection of engineering, interface quality, and business needs." /><div className="mt-7 space-y-5 text-base leading-8 text-slate-600"><p>My work spans full stack development, frontend engineering, WordPress, WooCommerce, Elementor, responsive design, APIs, databases, technical SEO, and performance optimization.</p><p>I approach a website or application as a complete product system. The interface must communicate trust. The code must be maintainable. The content structure must support users and search engines. The responsive behavior must work beyond a single screenshot.</p><p>The goal is not to add complexity. It is to identify the right level of architecture, motion, component reuse, and operational discipline for the product being built.</p></div></div><div className="grid grid-cols-2 gap-4">{stats.map((stat) => <Card key={stat.label} className="p-6 sm:p-7"><p className="font-display text-4xl font-bold tracking-[-0.05em] text-navy"><Counter value={stat.value} suffix={stat.suffix} /></p><p className="mt-3 text-sm leading-6 text-slate-500">{stat.label}</p></Card>)}</div></div></section>
  <section className="section-space bg-surface"><div className="container-shell"><SectionHeading eyebrow="Career journey" title="Capability built in layers, with each discipline strengthening the next." description="The timeline reflects the progression from implementation skills toward complete product delivery." /><div className="relative mt-14 max-w-4xl before:absolute before:left-[19px] before:top-2 before:h-[calc(100%-1rem)] before:w-px before:bg-slate-300 sm:before:left-[159px]">{timeline.map((item) => <div key={item.period} className="relative grid gap-4 pb-10 pl-14 sm:grid-cols-[130px_1fr] sm:pl-0"><span className="absolute left-2.5 top-1.5 h-5 w-5 rounded-full border-[5px] border-surface bg-brand sm:left-[149px]" /><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand sm:pt-1">{item.period}</p><Card className="p-6 sm:ml-8"><h3 className="font-display text-xl font-bold text-navy">{item.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.text}</p></Card></div>)}</div></div></section>
  <section className="section-space bg-white"><div className="container-shell"><SectionHeading align="center" eyebrow="Direction" title="Mission, vision, values, and professional philosophy." /><div className="mt-12 grid gap-6 lg:grid-cols-2"><Card className="p-8"><Route className="h-8 w-8 text-brand" /><h3 className="mt-6 font-display text-2xl font-bold">Mission</h3><p className="mt-3 leading-8 text-slate-600">Build digital systems that help clients and teams move with more clarity, credibility, speed, and confidence.</p></Card><Card className="p-8"><Eye className="h-8 w-8 text-brand" /><h3 className="mt-6 font-display text-2xl font-bold">Vision</h3><p className="mt-3 leading-8 text-slate-600">Become a trusted engineering partner known for product-quality execution across modern web applications and WordPress ecosystems.</p></Card></div><div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{values.map(({ icon: Icon, title, text }) => <Card key={title} className="p-6"><Icon className="h-7 w-7 text-brand" /><h3 className="mt-5 font-display text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></Card>)}</div><Card className="mt-6 grid gap-7 p-8 lg:grid-cols-[auto_1fr] lg:items-start"><Award className="h-9 w-9 text-brand" /><div><h3 className="font-display text-2xl font-bold">Professional philosophy</h3><p className="mt-3 leading-8 text-slate-600">The best implementation is not the most complicated one. It is the one that solves the right problem, protects the user experience, supports future changes, and can be understood by the people responsible for it.</p></div></Card></div></section>
  <section className="bg-surface py-20"><div className="container-shell grid gap-6 md:grid-cols-2"><Card className="p-8"><GraduationCap className="h-8 w-8 text-brand" /><h2 className="mt-5 font-display text-2xl font-bold">Education mindset</h2><p className="mt-3 leading-8 text-slate-600">Formal learning is reinforced through implementation, documentation, code review, performance testing, and continuous study of modern web standards.</p></Card><Card className="p-8"><Award className="h-8 w-8 text-brand" /><h2 className="mt-5 font-display text-2xl font-bold">Achievements</h2><p className="mt-3 leading-8 text-slate-600">The portfolio emphasizes reusable systems, responsive delivery, performance targets, certifications, and the ability to work across both application and CMS ecosystems.</p></Card></div></section><ContactCta /></>;
}
